# Generated by Django 5.0.6 on 2024-08-18 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default='0')),
                ('discount', models.IntegerField(default='100')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.faculty')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.level')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('video_name', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='videos/')),
                ('thumbnil', models.ImageField(blank=True, null=True, upload_to='thumbnils/')),
                ('description', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.teacher')),
            ],
        ),
    ]
