# Generated by Django 5.0.6 on 2024-08-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='offer_time',
            field=models.IntegerField(default='365'),
        ),
    ]
