# Generated by Django 5.0.6 on 2024-06-05 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_imageupload_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='title',
        ),
    ]
