# Generated by Django 5.0.6 on 2024-07-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SliderItem',
            new_name='Slider',
        ),
    ]
