# Generated by Django 5.0.6 on 2024-08-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
