# Generated by Django 5.0.6 on 2024-08-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentic', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
